name: Check Signed-off-by in PR
description: Ensure PRs contain Signed-off-by
branding:
  icon: check
  color: blue
inputs:
  token:
    description: Github token to comment on the PR
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        COMMITS_URL: ${{ github.event.pull_request.commits_url }}
      run: |
        echo "$COMMITS_URL"
        commits="${curl -s -H "Authorization: token $GITHUB_TOKEN" "$COMMITS_URL"}"
        echo $commits
